version: '3.6'
services:
  db:
    image: mysql
    container_name: sun_hotel
    hostname: localhost
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../db/script_inicial.sql:/docker-entrypoint-initdb.d/script_inicial.sql